// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJIPlvsK_K7nKckP2BYO06xjLPzghf_3k',
    appId: '1:276783527571:web:805d60e57d93935114bf66',
    messagingSenderId: '276783527571',
    projectId: 'scancart-clone',
    authDomain: 'scancart-clone.firebaseapp.com',
    storageBucket: 'scancart-clone.appspot.com',
    measurementId: 'G-RQF4P2NYYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWWvcF3g2QMpDyXH3myUxAMCHbui96UwU',
    appId: '1:276783527571:android:ae294214f9b6d72014bf66',
    messagingSenderId: '276783527571',
    projectId: 'scancart-clone',
    storageBucket: 'scancart-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNoht3EN6XOFHHX8J6UDijVQqd3v4MU9E',
    appId: '1:276783527571:ios:b73048b8639d70e014bf66',
    messagingSenderId: '276783527571',
    projectId: 'scancart-clone',
    storageBucket: 'scancart-clone.appspot.com',
    androidClientId: '276783527571-usme30ne6mml7cdsnsgdpuajq8ftmmdp.apps.googleusercontent.com',
    iosClientId: '276783527571-u1ig6quiig1k2c6gt4671rpchslbrsba.apps.googleusercontent.com',
    iosBundleId: 'com.io.scanCartClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNoht3EN6XOFHHX8J6UDijVQqd3v4MU9E',
    appId: '1:276783527571:ios:b73048b8639d70e014bf66',
    messagingSenderId: '276783527571',
    projectId: 'scancart-clone',
    storageBucket: 'scancart-clone.appspot.com',
    androidClientId: '276783527571-usme30ne6mml7cdsnsgdpuajq8ftmmdp.apps.googleusercontent.com',
    iosClientId: '276783527571-u1ig6quiig1k2c6gt4671rpchslbrsba.apps.googleusercontent.com',
    iosBundleId: 'com.io.scanCartClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJIPlvsK_K7nKckP2BYO06xjLPzghf_3k',
    appId: '1:276783527571:web:0394b867ac0272ef14bf66',
    messagingSenderId: '276783527571',
    projectId: 'scancart-clone',
    authDomain: 'scancart-clone.firebaseapp.com',
    storageBucket: 'scancart-clone.appspot.com',
    measurementId: 'G-Y03HLJ35GP',
  );
}
